#!/bin/bash

# Generate .env files for the web and admin apps.
# Each app gets its own .env in its directory.

set -e

GREEN="\033[0;32m"
BLUE="\033[0;34m"
NC="\033[0m"

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
WEB_DIR="$ROOT_DIR/apps/web"
ADMIN_DIR="$ROOT_DIR/apps/admin"

mkdir -p "$WEB_DIR" "$ADMIN_DIR"

# ------- Web app .env -------
WEB_ENV="$WEB_DIR/.env"
cat > "$WEB_ENV" <<EOF
# Generated by EnvMaker.sh
PORT=7000
HOSTNAME=0.0.0.0
BASE_PATH=/app
NODE_ENV=development

# Backend / file server URLs (override per environment)
SERVER_URL=http://localhost:8080
SERVER_URL_V=http://localhost:8080
FILE_SERVER_URL=http://localhost:8080/files
FILE_SERVER_URL_BASE=http://localhost:8080
ROOT_URL=http://localhost:82/app
WEB_URL=http://localhost:82/app
ADMIN_URL=http://localhost:82/app/admin
EOF

echo -e "${GREEN}✔ Wrote $WEB_ENV${NC}"

# ------- Admin app .env -------
ADMIN_ENV="$ADMIN_DIR/.env"
cat > "$ADMIN_ENV" <<EOF
# Generated by EnvMaker.sh
PORT=7100
HOSTNAME=0.0.0.0
BASE_PATH=/admin
NODE_ENV=development

# Backend / file server URLs (override per environment)
SERVER_URL=http://localhost:8080
SERVER_URL_V=http://localhost:8080
FILE_SERVER_URL=http://localhost:8080/files
FILE_SERVER_URL_BASE=http://localhost:8080
ROOT_URL=http://localhost:82/app/admin
WEB_URL=http://localhost:82/app
ADMIN_URL=http://localhost:82/app/admin
EOF

echo -e "${GREEN}✔ Wrote $ADMIN_ENV${NC}"

echo -e "${BLUE}🎉 Done. Edit the files above to point at your environment.${NC}"
